export const statsData = [
  {
    icon: 'bxs-user',
    value: '1,234',
    label: 'Всего пользователей',
    trend: '12%',
    trendType: 'trend-up',
    accent: '#ff9000',
  },
  {
    icon: 'bxs-gift',
    value: '456',
    label: 'Активные рефералы',
    trend: '8%',
    trendType: 'trend-up',
    accent: '#ffd700',
  },
  {
    icon: 'bxs-book-content',
    value: '789',
    label: 'Всего тестов',
    trend: '15%',
    trendType: 'trend-up',
    accent: '#54a0ff',
  },
  {
    icon: 'bxs-crown',
    value: '567',
    label: 'Активные подписки',
    trend: '5%',
    trendType: 'trend-up',
    accent: '#ff9000',
  },
  {
    icon: 'bxs-wallet',
    value: '₸45,678',
    label: 'Общий доход',
    trend: '18%',
    trendType: 'trend-up',
    accent: '#00b894',
  },
  {
    icon: 'bxs-time',
    value: '12:45',
    label: 'Среднее время теста',
    trend: '3%',
    trendType: 'trend-down',
    accent: '#636e72',
  },
]; 